### ISSUE TITLE
trade secrets

### ISSUE THREAD

**Issue by Maxhodges** [ExodusMovement/exodus-linux-installer#9]
Your arguments don't make sense.

>Additionally, open-sourcing these elements can make it easier for hackers to make bootleg phishing versions of our wallet, and try to pass them off as official downloads.

"Hackers" could just as well make a bootleg phishing version without your source code. For example, hundreds of counterfeit apps masquerading as huge brands like Zappos and Nordstrom have made their way into the iOS App Store.

>Keeping a few trade secrets is important for the long term success of the company. 

When it comes to cryptography, the opposite is true.

http://support.exodus.io/article/89-is-exodus-open-source

**Comment by jprichardson** [comment]
In the future, please don't post unrelated topics to a repo...

You can see my Github profile, I'm a big supporter of OSS. I would like to OSS Exodus at some point. The original reason we didn't open source Exodus due to validating our business model - that's it. It was a business decision.

We will reevaluate our position again as we start building up our platform.

**Comment by Maxhodges** [comment]
I guess you validated it if you can afford to pay $60K to customer support
reps now ;)
